### ISSUE TITLE
Product details

### ISSUE THREAD

**Issue by gabrielrtakeda** [gabrielrtakeda/shopping-cart#5]
# Description
> Product details

### Task List
- [x] Product details UI
- [x] Add `price` and `quantity` to `Product` schema
- [x] GraphQL query to fetch details
