### ISSUE TITLE
Add to cart logic

### ISSUE THREAD

**Issue by gabrielrtakeda** [gabrielrtakeda/shopping-cart#6]
# Description
> Product buy logic

### Task List
- [x] Cart schema
- [x] Cart schema operations
- [x] Add to cart UI interactions
- [x] GraphQL mutation to update `Product` stock quantity
- [x] GraphQL mutation to update `Cart` items
