### ISSUE TITLE
Cart management logic

### ISSUE THREAD

**Issue by gabrielrtakeda** [gabrielrtakeda/shopping-cart#8]
# Description
> Cart management logic

### Task List
- [x] UI to increase or decrease `Product` quantity
- [x] UI to remove a `Product` from `Cart`
- [x] mutation to increase or decrease `Product` quantity
- [x] mutation to remove a `Product` from `Cart`
- [x] behaviour to **refetch** queries after mutation's call
